import type { AppView, ReleaseCandidate, ReleaseCandidateRequest, ReleaseCheckProfile, ReleaseConfig, ReleaseFileChange, ReleaseFileClassification, ReleaseFileRule, ReleaseLog, ReleaseManualDecision, ReleasePreflight, ReleaseRun, ReleaseTarget, ReleaseVersionGroup, ReleaseVersionMode, SelectedReleaseTarget, VersionStrategy } from '@/types';
import type { ReleaseArtifact, ReleaseAutomationStatus, ReleaseTargetRun } from '@/types/releaseExecution';
import type { ComputedRef, Ref } from 'vue';
import type { ReleasePreferences } from '@/utils/releasePreferences';
export type ExecutionPhase = 'build' | 'package' | 'publish' | 'deploy';
export type ReleaseBuildPlan = 'cloud' | 'local-publish' | 'local-current' | 'local-upgrade';
export type TargetChoice = {
    selected: boolean;
} & Record<ExecutionPhase, boolean>;
export type ProductPlatformId = 'web' | 'pc' | 'android' | 'mac' | 'server' | `custom:${string}`;
export type ProductPlatform = {
    id: ProductPlatformId;
    name: string;
    icon: string;
    description: string;
    targets: ReleaseTarget[];
    configured: boolean;
};
export type ReleaseTab = 'publish' | 'settings';
export type PlannedVersion = {
    versionGroupId: string;
    versionGroupName: string;
    currentVersion: string;
    suggestedVersion: string;
    targetVersion: string;
    tagName: string;
};
export interface ReleaseContext {
    props: {
        app: AppView;
    };
    emit: (e: 'close') => void;
    phaseOptions: ComputedRef<Array<{
        key: ExecutionPhase;
        label: string;
        hint: string;
        risky: boolean;
    }>>;
    loading: Ref<boolean, boolean>;
    savingProfile: Ref<boolean, boolean>;
    publishing: Ref<boolean, boolean>;
    autoSubmitting: Ref<boolean, boolean>;
    unstaging: Ref<boolean, boolean>;
    unstageNotice: Ref<string, string>;
    error: Ref<string, string>;
    errorCode: Ref<string, string>;
    versionPlanNotice: Ref<string, string>;
    preflight: Ref<ReleasePreflight | null>;
    history: Ref<ReleaseRun[]>;
    selected: Ref<Record<string, boolean>>;
    releaseIntent: Ref<'formal' | 'save-progress'>;
    manualDecisions: Ref<ReleaseManualDecision[]>;
    sensitiveExceptions: Ref<NonNullable<ReleaseCandidateRequest['sensitiveExceptions']>>;
    candidate: Ref<ReleaseCandidate | null>;
    checkingCandidate: Ref<boolean, boolean>;
    ignoringFile: Ref<boolean>;
    ignoreSafetyFile: (file: ReleaseFileClassification) => Promise<string>;
    checksEnabled: Ref<boolean, boolean>;
    candidateSignature: Ref<string, string>;
    reviewSignature: Ref<string, string>;
    findingDecisions: Ref<Record<string, 'allow' | 'exclude'>>;
    resolvingReview: Ref<boolean, boolean>;
    safetySettingsDirty: Ref<boolean, boolean>;
    candidatePoll: ReturnType<typeof setTimeout> | null;
    candidateEpoch: number;
    candidateAbort: AbortController | null;
    safetyFiles: ComputedRef<ReleaseFileClassification[]>;
    candidateRequest: ComputedRef<ReleaseCandidateRequest>;
    currentCandidateSignature: ComputedRef<string>;
    submissionPlanSignature: ComputedRef<string>;
    candidateStale: ComputedRef<boolean>;
    reviewStale: ComputedRef<boolean>;
    pendingFindings: ComputedRef<ReleaseCandidate["sensitiveFindings"]>;
    candidateReady: ComputedRef<boolean>;
    candidateNeedsAttention: ComputedRef<boolean>;
    showReleaseIssues: () => Promise<void>;
    chooseSafetyFile: (file: ReleaseFileClassification, included: boolean) => void;
    adoptRecommended: () => void;
    recordSensitiveException: (finding: ReleaseCandidate["sensitiveFindings"][number], reason: string) => void;
    continueResolvedReview: () => void;
    changeReleaseIntent: (intent: "formal" | "save-progress") => void;
    refreshSafety: () => Promise<void>;
    inspectCandidate: () => Promise<boolean>;
    cancelCandidate: () => Promise<void>;
    saveSafetyConfig: (rules: ReleaseFileRule[], checks: ReleaseCheckProfile[]) => Promise<void>;
    versionInputs: Ref<Record<string, string>>;
    commitMessage: Ref<string, string>;
    commitMessageDirty: Ref<boolean, boolean>;
    releaseNotes: Ref<string, string>;
    releaseNotesDirty: Ref<boolean, boolean>;
    releaseNotesStale: Ref<boolean, boolean>;
    releaseNotesLoading: Ref<boolean, boolean>;
    releaseNotesError: Ref<string, string>;
    releaseNotesBaseTag: Ref<string, string>;
    releaseNotesSourceFingerprint: Ref<string, string>;
    releaseNotesGeneratedFor: Ref<string, string>;
    remoteName: Ref<string, string>;
    versionStrategy: Ref<VersionStrategy>;
    preReleaseCommand: Ref<string, string>;
    createTag: Ref<boolean, boolean>;
    pushRemote: Ref<boolean, boolean>;
    buildMode: Ref<'github' | 'local'>;
    versionMode: Ref<ReleaseVersionMode>;
    profileReady: Ref<boolean, boolean>;
    preferenceStatus: Ref<'idle' | 'saving' | 'saved' | 'error'>;
    preferenceError: Ref<string, string>;
    preferenceRevision: number;
    editedReleaseOptions: Set<"build" | "push" | "targets" | "tag" | "version" | "intent" | "local-version" | "checks">;
    releaseConfig: Ref<ReleaseConfig | null>;
    configDraft: Ref<ReleaseConfig | null>;
    configBeforeEdit: Ref<ReleaseConfig | null>;
    targetChoices: Ref<Record<string, TargetChoice>>;
    configEndpointAvailable: Ref<boolean, boolean>;
    configNotice: Ref<string, string>;
    configEditorOpen: Ref<boolean, boolean>;
    configFileOpen: Ref<boolean, boolean>;
    configScanning: Ref<boolean, boolean>;
    configSaving: Ref<boolean, boolean>;
    configValidationError: Ref<string, string>;
    preflightStale: Ref<boolean, boolean>;
    gitOnly: Ref<boolean, boolean>;
    releaseTab: Ref<ReleaseTab>;
    tabScroll: Record<ReleaseTab, number>;
    configFileDirty: Ref<boolean, boolean>;
    confirmAction: Ref<'retry' | 'regenerate-notes' | null>;
    bodyRef: Ref<HTMLElement | null>;
    platformSectionRef: Ref<HTMLElement | null>;
    activeRun: Ref<ReleaseRun | null>;
    logs: Ref<ReleaseLog[]>;
    runTargets: Ref<ReleaseTargetRun[]>;
    runArtifacts: Ref<ReleaseArtifact[]>;
    runAutomation: Ref<ReleaseAutomationStatus | null>;
    runDeliveries: Ref<import('@/types/releaseExecution').ReleaseDelivery[]>;
    cloudBuild: Ref<import('@/types').CloudBuildStatus | null>;
    retrying: Ref<boolean, boolean>;
    openingAutomation: Ref<boolean, boolean>;
    automationOpenError: Ref<string, string>;
    retryMetadataLoaded: Ref<boolean, boolean>;
    retryConfirmationRequired: Ref<boolean | undefined>;
    retryConfirmationTargets: Ref<string[]>;
    pollTimer: ReturnType<typeof setTimeout> | null;
    preferenceTimer: ReturnType<typeof setTimeout> | null;
    releaseNotesTimer: ReturnType<typeof setTimeout> | null;
    releaseNotesRequest: number;
    preferenceSave: Promise<void>;
    disposed: boolean;
    isActive: ComputedRef<boolean>;
    selectedPaths: ComputedRef<string[]>;
    orderedChanges: ComputedRef<ReleaseFileChange[]>;
    newFiles: ComputedRef<ReleaseFileChange[]>;
    allFilesSelected: ComputedRef<boolean>;
    configuredTargets: ComputedRef<ReleaseTarget[]>;
    chosenTargets: ComputedRef<{
        target: ReleaseTarget;
        choice: TargetChoice;
    }[]>;
    selectedTargets: ComputedRef<SelectedReleaseTarget[]>;
    invalidChosenTargetIds: ComputedRef<string[]>;
    targetSelectionMissing: ComputedRef<boolean>;
    selectedVersionGroupIds: ComputedRef<string[]>;
    selectedVersionGroups: ComputedRef<ReleaseVersionGroup[]>;
    selectedVersionFiles: ComputedRef<string[]>;
    visibleCurrentVersions: ComputedRef<Record<string, string>>;
    isTagPushTarget: (target: ReleaseTarget) => boolean;
    plannedVersions: ComputedRef<PlannedVersion[]>;
    versionForGroup: (group: ReleaseVersionGroup) => PlannedVersion;
    platformVersions: (platform: ProductPlatform) => PlannedVersion[];
    displayCurrentVersion: (value: string) => string;
    versionPattern: RegExp;
    versionValid: ComputedRef<boolean>;
    primaryTargetVersion: ComputedRef<string>;
    plannedTagNames: ComputedRef<string[]>;
    configNeedsSaving: ComputedRef<boolean>;
    selectedNeedsRemotePush: ComputedRef<boolean>;
    configuredAutomation: ComputedRef<{
        account?: string | undefined;
        provider: string;
        workflow: string;
        trigger: string;
        releaseBranch: string;
        publishesRelease: boolean;
    } | null>;
    selectedHasTagPushTarget: ComputedRef<boolean>;
    automationTargetRequiresTag: ComputedRef<boolean>;
    willTriggerAutomation: ComputedRef<boolean>;
    automationBranchMismatch: ComputedRef<boolean>;
    willBuildWindowsInAutomation: ComputedRef<boolean>;
    willBuildTargetsInAutomation: ComputedRef<boolean>;
    releaseNotesOptionsSignature: ComputedRef<string>;
    targetSelectionValid: ComputedRef<boolean>;
    newContentState: ComputedRef<"none" | "unknown" | "new">;
    releaseContentHint: ComputedRef<string>;
    blockingIssues: ComputedRef<ReleasePreflight["blockingIssues"]>;
    localChecksPassed: ComputedRef<boolean>;
    remoteMissing: ComputedRef<boolean>;
    canSubmit: ComputedRef<boolean>;
    canPublish: ComputedRef<boolean>;
    canRetryRun: (run: ReleaseRun | null | undefined) => boolean;
    retryable: ComputedRef<boolean>;
    customRetryConfirmation: ComputedRef<boolean>;
    retryUpload: ComputedRef<boolean>;
    uploadPaused: ComputedRef<boolean>;
    runFailureSummary: ComputedRef<string>;
    runFailureDetails: ComputedRef<string>;
    retryButtonLabel: ComputedRef<string>;
    retryGuidance: ComputedRef<string>;
    retryTargetNames: ComputedRef<string>;
    hasOnlineAction: ComputedRef<boolean>;
    hasExternalAction: ComputedRef<boolean>;
    remoteDestination: ComputedRef<string>;
    automationPageUrl: ComputedRef<string>;
    openAutomationPage: () => Promise<void>;
    automationHandedOff: ComputedRef<boolean>;
    activeRunStatusLabel: ComputedRef<string>;
    activeStageLabel: ComputedRef<string>;
    cloudExecutionNotice: ComputedRef<{
        title: string;
        text: string;
    } | null>;
    cloudBuildSettled: ComputedRef<boolean>;
    completionTitle: ComputedRef<string>;
    completionDescription: ComputedRef<string>;
    confirmDialogTitle: ComputedRef<string>;
    confirmDialogMessage: ComputedRef<string>;
    confirmDialogButton: ComputedRef<string>;
    configConfidence: ComputedRef<number>;
    standardPlatforms: ComputedRef<Array<{
        id: Exclude<ProductPlatformId, `custom:${string}`>;
        name: string;
        icon: string;
        description: string;
    }>>;
    platformIdForTarget: (target: ReleaseTarget) => ProductPlatformId | null;
    versionGroupDisplayName: (group: ReleaseVersionGroup) => string;
    productPlatforms: ComputedRef<ProductPlatform[]>;
    visibleProductPlatforms: ComputedRef<ProductPlatform[]>;
    phaseAllowed: (phase: ExecutionPhase) => boolean;
    selectedDelivery: ComputedRef<boolean>;
    syncPolicy: Ref<'auto' | 'local'>;
    localSyncPolicy: Ref<'auto' | 'local'>;
    localVersionMode: Ref<'current' | 'upgrade'>;
    localBuildOnly: ComputedRef<boolean>;
    changeLocalVersionMode: (mode: 'current' | 'upgrade') => void;
    syncRepository: ComputedRef<string>;
    syncDeliveryMissing: ComputedRef<boolean>;
    syncNotice: ComputedRef<string>;
    applySyncPolicy: () => void;
    changeSyncPolicy: (policy: 'auto' | 'local') => void;
    buildPlan: ComputedRef<ReleaseBuildPlan>;
    changeBuildPlan: (plan: ReleaseBuildPlan) => void;
    changeBuildMode: (mode: "github" | "local") => void;
    configuredActions: (target: ReleaseTarget) => {
        key: ExecutionPhase;
        label: string;
        hint: string;
        risky: boolean;
    }[];
    platformRunnableTargets: (platform: ProductPlatform) => ReleaseTarget[];
    platformSelected: (platform: ProductPlatform) => boolean;
    platformHasSelection: (platform: ProductPlatform) => boolean;
    platformPartiallySelected: (platform: ProductPlatform) => boolean;
    platformPartiallyAvailable: (platform: ProductPlatform) => boolean;
    platformSelectionCount: (platform: ProductPlatform) => {
        selected: number;
        runnable: number;
        total: number;
    };
    platformUnavailableReason: (platform: ProductPlatform) => string;
    platformActionLabels: (platform: ProductPlatform, selectedOnly?: boolean) => string[];
    platformCardDetail: (platform: ProductPlatform) => string;
    togglePlatform: (platform: ProductPlatform, checked: boolean) => void;
    selectSingleBuildPlatform: (enteringRelease?: boolean) => void;
    toggleGitOnly: (checked: boolean) => void;
    stageLabel: ComputedRef<Record<string, string>>;
    targetStageLabel: ComputedRef<Record<string, string>>;
    summaryLines: ComputedRef<string[]>;
    messageOf: (reason: unknown) => string;
    githubRepositoryUrl: (remoteUrl: string) => string;
    githubActionsUrl: (remoteUrl: string, workflow: string) => string;
    nextPatchVersion: (values: string[]) => string;
    suggestReleaseVersion: (currentVersions: string[], latestTag: string) => string;
    cloneConfig: (config: ReleaseConfig) => ReleaseConfig;
    normalizeConfig: (raw: ReleaseConfig) => ReleaseConfig;
    currentOS: () => "windows" | "darwin" | "linux";
    osLabel: (os: string) => string;
    targetUnavailableReason: (target: ReleaseTarget) => string;
    targetPhaseHint: (target: ReleaseTarget, phase: {
        key: ExecutionPhase;
        label: string;
        hint: string;
        risky: boolean;
    }) => string;
    targetAvailable: (target: ReleaseTarget) => boolean;
    defaultTargetChoice: (target: ReleaseTarget) => TargetChoice;
    applyReleaseConfig: (raw: ReleaseConfig, editing?: boolean) => void;
    resetSelection: (pf: ReleasePreflight) => void;
    fileStatusLabel: (file: ReleaseFileChange) => string;
    isAddedFile: (file: ReleaseFileChange) => boolean;
    selectAllFiles: (checked: boolean) => void;
    normalizePreflight: (pf: ReleasePreflight) => ReleasePreflight;
    preferenceKey: () => string;
    readLocalPreferences: () => ReleasePreferences;
    captureTargetPreferences: () => void;
    restoreTargetPreferences: () => boolean;
    rememberPreferences: () => void;
    saveRememberedPreferences: () => Promise<void>;
    closeModal: () => Promise<void>;
    setDefaultCommitMessage: (force?: boolean) => void;
    onCommitMessageInput: () => void;
    syncVersionInputs: () => void;
    scheduleReleaseNotesDraft: (delay?: number) => void;
    generateReleaseNotesDraft: (force?: boolean, overwriteConfirmed?: boolean) => Promise<void>;
    onReleaseNotesInput: () => void;
    applyPreflight: (raw: ReleasePreflight, initial?: boolean, resetFiles?: boolean) => void;
    unstageFiles: () => Promise<void>;
    load: () => Promise<void>;
    profileBody: () => {
        buildMode: "github" | "local";
        syncPolicy: "auto" | "local";
        remoteName: string;
        versionStrategy: VersionStrategy;
        preReleaseCommand: string;
        createTag: boolean;
        versionMode: ReleaseVersionMode;
    };
    saveAndRecheck: () => Promise<void>;
    onVersionInput: (groupID: string, value: string) => void;
    onCreateTagChange: () => void;
    onVersionModeChange: () => void;
    setTargetSelected: (targetId: string, checked: boolean) => void;
    setTargetPhase: (targetId: string, phase: ExecutionPhase, checked: boolean) => void;
    versionGroupName: (target: ReleaseTarget) => string;
    scanReleaseConfig: () => Promise<void>;
    openConfigEditor: () => void;
    cancelConfigEdit: () => void;
    validateConfig: (config: ReleaseConfig) => string;
    saveReleaseConfig: () => Promise<void>;
    switchReleaseTab: (tab: ReleaseTab, focus?: boolean) => Promise<void>;
    chooseReleaseTarget: () => Promise<void>;
    onReleaseTabKeydown: (event: KeyboardEvent) => void;
    onConfigFileSaved: (config: ReleaseConfig) => Promise<void>;
    newId: (prefix: string, existing: string[]) => string;
    addVersionGroup: () => void;
    removeVersionGroup: (index: number) => void;
    addVersionFile: (group: ReleaseVersionGroup) => void;
    addTarget: () => void;
    setRunnerOS: (target: ReleaseTarget, os: string, checked: boolean) => void;
    setArtifacts: (target: ReleaseTarget, value: string) => void;
    submitRelease: () => Promise<void>;
    publish: () => Promise<void>;
    prepareLocalCommit: () => void;
    releaseErrorMessage: (reason: unknown) => string;
    showRun: (run: ReleaseRun) => void;
    historyStatus: (run: ReleaseRun) => string;
    schedulePoll: (delay?: number) => void;
    poll: () => Promise<void>;
    retry: (externalActionsConfirmed?: boolean) => Promise<void>;
    confirmSensitiveAction: () => Promise<void>;
    startNew: () => void;
}
